<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\IQ.Mofy.Core\IQ.Mofy.Core.csproj" />
    <ProjectReference Include="..\IQ.Mofy.Data.Abstractions\IQ.Mofy.Data.Abstractions.csproj" />
  </ItemGroup>

</Project>
